name = "xi-syntect-plugin"
version = "0.0.0"
scope = "global"
exec_path = "./bin/xi-syntect-plugin"
activations = ["autorun"]
commands = []

[[languages]]
name = "Plain Text"
extensions = ["txt"]
scope = "text.plain"

[[languages]]
name = "ASP"
extensions = ["asa"]
scope = "source.asp"

[[languages]]
name = "HTML (ASP)"
extensions = ["asp"]
scope = "text.html.asp"

[[languages]]
name = "ActionScript"
extensions = ["as"]
scope = "source.actionscript.2"

[[languages]]
name = "AppleScript"
extensions = ["applescript", "script editor"]
first_line_match = "^#!.*(osascript)"
scope = "source.applescript"

[[languages]]
name = "Batch File"
extensions = ["bat", "cmd"]
scope = "source.dosbatch"

[[languages]]
name = "NAnt Build File"
extensions = ["build"]
scope = "source.nant-build"

[[languages]]
name = "C#"
extensions = ["cs", "csx"]
scope = "source.cs"

[[languages]]
name = "C++"
extensions = ["cpp", "cc", "cp", "cxx", "c++", "C", "h", "hh", "hpp", "hxx", "h++", "inl", "ipp"]
first_line_match = "-\\*- C\\+\\+ -\\*-"
scope = "source.c++"

[[languages]]
name = "C"
extensions = ["c", "h"]
first_line_match = "-[*]-( Mode:)? C -[*]-"
scope = "source.c"

[[languages]]
name = "CSS"
extensions = ["css", "css.erb", "css.liquid"]
scope = "source.css"

[[languages]]
name = "Clojure"
extensions = ["clj", "cljc", "cljs", "edn"]
scope = "source.clojure"

[[languages]]
name = "D"
extensions = ["d", "di"]
first_line_match = "^#!.*\\bg?dmd\\b."
scope = "source.d"

[[languages]]
name = "Diff"
extensions = ["diff", "patch"]
first_line_match = "(?x)^\n    (===\\ modified\\ file\n    |==== \\s* // .+ \\s - \\s .+ \\s+ ====\n    |Index:[ ]\n    |---\\ [^%]\n    |\\*\\*\\*.*\\d{4}\\s*$\n    |\\d+(,\\d+)* (a|d|c) \\d+(,\\d+)* $\n    |diff\\ --git[ ]\n    )"
scope = "source.diff"

[[languages]]
name = "Erlang"
extensions = ["erl", "hrl", "Emakefile", "emakefile"]
scope = "source.erlang"

[[languages]]
name = "HTML (Erlang)"
extensions = ["yaws"]
scope = "text.html.erlang.yaws"

[[languages]]
name = "Git Attributes"
extensions = ["attributes", "gitattributes", ".gitattributes"]
scope = "text.git.attributes"

[[languages]]
name = "Git Commit"
extensions = ["COMMIT_EDITMSG", "MERGE_MSG", "TAG_EDITMSG"]
scope = "text.git.commit"

[[languages]]
name = "Git Config"
extensions = ["gitconfig", ".gitconfig", ".gitmodules"]
first_line_match = "^\\[core\\]"
scope = "text.git.config"

[[languages]]
name = "Git Ignore"
extensions = ["exclude", "gitignore", ".gitignore"]
scope = "text.git.ignore"

[[languages]]
name = "Git Link"
extensions = [".git"]
first_line_match = "^\\s*gitdir\\s*:"
scope = "text.git.link"

[[languages]]
name = "Git Log"
extensions = ["gitlog"]
first_line_match = "commit\\s+\\h{7,}"
scope = "text.git.log"

[[languages]]
name = "Git Rebase Todo"
extensions = ["git-rebase-todo"]
first_line_match = "^(?:drop|edit|exec|fixup|pick|reword|squash|[defprsx]) \\h{7,} "
scope = "text.git.rebase"

[[languages]]
name = "Go"
extensions = ["go"]
first_line_match = "-[*]-( Mode:)? Go -[*]-"
scope = "source.go"

[[languages]]
name = "Graphviz (DOT)"
extensions = ["dot", "DOT", "gv"]
scope = "source.dot"

[[languages]]
name = "Groovy"
extensions = ["groovy", "gvy", "gradle", "Jenkinsfile"]
scope = "source.groovy"

[[languages]]
name = "HTML"
extensions = ["html", "htm", "shtml", "xhtml"]
first_line_match = "(?i)<(!DOCTYPE\\s*)?html"
scope = "text.html.basic"

[[languages]]
name = "Haskell"
extensions = ["hs"]
scope = "source.haskell"

[[languages]]
name = "Literate Haskell"
extensions = ["lhs"]
scope = "text.tex.latex.haskell"

[[languages]]
name = "Java Server Page (JSP)"
extensions = ["jsp"]
scope = "text.html.jsp"

[[languages]]
name = "Java"
extensions = ["java", "bsh"]
scope = "source.java"

[[languages]]
name = "Java Properties"
extensions = ["properties"]
scope = "source.java-props"

[[languages]]
name = "JSON"
extensions = ["json", "sublime-settings", "sublime-menu", "sublime-keymap", "sublime-mousemap", "sublime-theme", "sublime-build", "sublime-project", "sublime-completions", "sublime-commands", "sublime-macro", "sublime-color-scheme", "ipynb", "Pipfile.lock"]
scope = "source.json"

[[languages]]
name = "JavaScript"
extensions = ["js", "htc"]
first_line_match = "^#!\\s*/.*\\b(node|js)\\b"
scope = "source.js"

[[languages]]
name = "BibTeX"
extensions = ["bib"]
scope = "text.bibtex"

[[languages]]
name = "LaTeX"
extensions = ["tex", "ltx"]
scope = "text.tex.latex"

[[languages]]
name = "TeX"
extensions = ["sty", "cls"]
scope = "text.tex"

[[languages]]
name = "Lisp"
extensions = ["lisp", "cl", "clisp", "l", "mud", "el", "scm", "ss", "lsp", "fasl"]
scope = "source.lisp"

[[languages]]
name = "Lua"
extensions = ["lua"]
scope = "source.lua"

[[languages]]
name = "Makefile"
extensions = ["make", "GNUmakefile", "makefile", "Makefile", "makefile.am", "Makefile.am", "makefile.in", "Makefile.in", "OCamlMakefile", "mak", "mk"]
first_line_match = "^#!\\s*/usr/bin/make\\b"
scope = "source.makefile"

[[languages]]
name = "Markdown"
extensions = ["md", "mdown", "markdown", "markdn"]
scope = "text.html.markdown"

[[languages]]
name = "MATLAB"
extensions = ["matlab"]
scope = "source.matlab"

[[languages]]
name = "OCaml"
extensions = ["ml", "mli"]
scope = "source.ocaml"

[[languages]]
name = "OCamllex"
extensions = ["mll"]
scope = "source.ocamllex"

[[languages]]
name = "OCamlyacc"
extensions = ["mly"]
scope = "source.ocamlyacc"

[[languages]]
name = "Objective-C++"
extensions = ["mm", "M", "h"]
scope = "source.objc++"

[[languages]]
name = "Objective-C"
extensions = ["m", "h"]
scope = "source.objc"

[[languages]]
name = "PHP"
extensions = ["php", "php3", "php4", "php5", "php7", "phps", "phpt", "phtml"]
first_line_match = "^(#!.*[^-]php[0-9]?|<\\?php)\\b"
scope = "embedding.php"

[[languages]]
name = "Pascal"
extensions = ["pas", "p", "dpr"]
scope = "source.pascal"

[[languages]]
name = "Perl"
extensions = ["pl", "pm", "pod", "t", "PL"]
first_line_match = "^#!.*\\bperl\\b"
scope = "source.perl"

[[languages]]
name = "Python"
extensions = ["py", "py3", "pyw", "pyi", "pyx", "pyx.in", "pxd", "pxd.in", "pxi", "pxi.in", "rpy", "cpy", "SConstruct", "Sconstruct", "sconstruct", "SConscript", "gyp", "gypi", "Snakefile", "wscript"]
first_line_match = "^#!\\s*/.*\\bpython(\\d(\\.\\d)?)?\\b"
scope = "source.python"

[[languages]]
name = "R"
extensions = ["R", "r", "s", "S", "Rprofile"]
scope = "source.r"

[[languages]]
name = "Rd (R Documentation)"
extensions = ["rd"]
scope = "text.tex.latex.rd"

[[languages]]
name = "HTML (Rails)"
extensions = ["rails", "rhtml", "erb", "html.erb"]
scope = "text.html.ruby"

[[languages]]
name = "JavaScript (Rails)"
extensions = ["js.erb"]
scope = "source.js.rails"

[[languages]]
name = "Ruby Haml"
extensions = ["haml", "sass"]
scope = "text.haml"

[[languages]]
name = "Ruby on Rails"
extensions = ["rxml", "builder"]
scope = "source.ruby.rails"

[[languages]]
name = "SQL (Rails)"
extensions = ["erbsql", "sql.erb"]
scope = "source.sql.ruby"

[[languages]]
name = "Regular Expression"
extensions = ["re"]
scope = "source.regexp"

[[languages]]
name = "reStructuredText"
extensions = ["rst", "rest"]
scope = "text.restructuredtext"

[[languages]]
name = "Ruby"
extensions = ["rb", "Appfile", "Appraisals", "Berksfile", "Brewfile", "capfile", "cgi", "Cheffile", "config.ru", "Deliverfile", "Fastfile", "fcgi", "Gemfile", "gemspec", "Guardfile", "irbrc", "jbuilder", "Podfile", "podspec", "prawn", "rabl", "rake", "Rakefile", "Rantfile", "rbx", "rjs", "ruby.rail", "Scanfile", "simplecov", "Snapfile", "thor", "Thorfile", "Vagrantfile"]
first_line_match = "^#!\\s*/.*\\bj?ruby\\b"
scope = "source.ruby"

[[languages]]
name = "Rust"
extensions = ["rs"]
scope = "source.rust"

[[languages]]
name = "SQL"
extensions = ["sql", "ddl", "dml"]
scope = "source.sql"

[[languages]]
name = "Scala"
extensions = ["scala", "sbt", "sc"]
scope = "source.scala"

[[languages]]
name = "Bourne Again Shell (bash)"
extensions = ["sh", "bash", "zsh", ".bash_aliases", ".bash_completions", ".bash_functions", ".bash_login", ".bash_logout", ".bash_profile", ".bash_variables", ".bashrc", ".profile", ".textmate_init", ".zlogin", ".zlogout", ".zprofile", ".zshenv", ".zshrc", "PKGBUILD", ".ebuild", ".eclass"]
first_line_match = "(?x)                     # ignore whitespace in this regex\n  ^                      # assert start of the line\n  \\#!                    # shebang token\n  .*                     # any characters\n  \\b(bash|zsh|sh|tcsh)\\b # \"bash\" or \"zsh\" or \"sh\" or \"tcsh\"\n  |                      # ... or ...\n  ^                      # assert start of the line\n  \\#                     # literal \"#\" character\n  \\s*                    # any whitespace\n  -\\*-                   # literal \"-*-\" string\n  [^*]*                  # any characters except \"*\"\n  mode:                  # literal \"mode:\" string\n  \\s*                    # any whitespace\n  shell-script           # literal \"shell-script\" string\n  [^*]*                  # any characters except \"*\"\n  -\\*-                   # literal \"-*-\" string\n"
scope = "source.shell.bash"

[[languages]]
name = "HTML (Tcl)"
extensions = ["adp"]
scope = "text.html.tcl"

[[languages]]
name = "Tcl"
extensions = ["tcl"]
scope = "source.tcl"

[[languages]]
name = "Textile"
extensions = ["textile"]
first_line_match = "textile"
scope = "text.html.textile"

[[languages]]
name = "TOML"
extensions = ["toml", "tml", "Cargo.lock", "Gopkg.lock", "Pipfile", "xiconfig"]
scope = "source.toml"

[[languages]]
name = "XML"
extensions = ["xml", "xsd", "xslt", "tld", "dtml", "rss", "opml", "svg"]
first_line_match = "(?x)\n^(?:\n    <\\?xml\\s\n |  \\s*<([\\w-]+):Envelope\\s+xmlns:\\1\\s*=\\s*\"http://schemas.xmlsoap.org/soap/envelope/\"\\s*>\n )"
scope = "text.xml"

[[languages]]
name = "YAML"
extensions = ["yaml", "yml", "sublime-syntax"]
first_line_match = "^%YAML( ?1.\\d+)?"
scope = "source.yaml"
