use_small_heuristics = true
force_explicit_abi = true
max_width = 120
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_modules = true
tab_spaces = 4
use_field_init_shorthand = false
use_try_shorthand = true