#!/bin/bash

GIT_ROOT="$(git rev-parse --show-toplevel)"

FILES=$(find "$GIT_ROOT/rust" -name Cargo.toml)
for i in ${FILES[@]}; do
    pushd $(dirname $i) > /dev/null
    if [[ $i == "$GIT_ROOT/rust/experimental/lang/Cargo.toml" ]]; then
        popd > /dev/null
        continue
    fi
    if ! cargo check; then
        echo $?
        echo $i
        break
    fi
    if ! cargo check --tests; then
        echo $i
        break
    fi
    popd > /dev/null
done
